//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris.wsOpinat {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="app.modules.ws.controllers.ApiSoapControllerPort", Namespace="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1", ConfigurationName="wsOpinat.appmoduleswscontrollersApiSoapControllerPort")]
    public interface appmoduleswscontrollersApiSoapControllerPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string apiLogin(object username, object password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiLogin", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> apiLoginAsync(object username, object password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiTestWithLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string apiTestWithLogin(object sessionkey, object dummytext);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiTestWithLogin", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> apiTestWithLoginAsync(object sessionkey, object dummytext);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiTestWithoutLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string apiTestWithoutLogin(object dummytext);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiTestWithoutLogin", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> apiTestWithoutLoginAsync(object dummytext);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiGetTemplateForTokenId" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string apiGetTemplateForTokenId(object sessionkey, object id, string skey, string resptype);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiGetTemplateForTokenId" +
            "", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> apiGetTemplateForTokenIdAsync(object sessionkey, object id, string skey, string resptype);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiGetTemplateForWaveId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string apiGetTemplateForWaveId(object sessionkey, object id, string lang_id, string resptype);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiGetTemplateForWaveId", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> apiGetTemplateForWaveIdAsync(object sessionkey, object id, string lang_id, string resptype);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiLoadSurveys", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string apiLoadSurveys(object sessionkey, object items_list);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiLoadSurveys", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> apiLoadSurveysAsync(object sessionkey, object items_list);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiLoadSurveyAnswers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string apiLoadSurveyAnswers(object sessionkey, object id, string skey, object answers_list);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiLoadSurveyAnswers", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> apiLoadSurveyAnswersAsync(object sessionkey, object id, string skey, object answers_list);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiLoadAudio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string apiLoadAudio(object sessionkey, object id, string skey, object answers_list);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiLoadAudio", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> apiLoadAudioAsync(object sessionkey, object id, string skey, object answers_list);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiGetMonthlyNpsInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string apiGetMonthlyNpsInfo(object sessionkey, int center, int campaign, int wave, int param_num, int param_value, int months);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiGetMonthlyNpsInfo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> apiGetMonthlyNpsInfoAsync(object sessionkey, int center, int campaign, int wave, int param_num, int param_value, int months);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiCreateWave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string apiCreateWave(object sessionkey, object wave_fields);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bo-emea.opinat.com/index.php/ws/api-soap/ws?ws=1#apiCreateWave", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> apiCreateWaveAsync(object sessionkey, object wave_fields);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface appmoduleswscontrollersApiSoapControllerPortChannel : Iris.wsOpinat.appmoduleswscontrollersApiSoapControllerPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class appmoduleswscontrollersApiSoapControllerPortClient : System.ServiceModel.ClientBase<Iris.wsOpinat.appmoduleswscontrollersApiSoapControllerPort>, Iris.wsOpinat.appmoduleswscontrollersApiSoapControllerPort {
        
        public appmoduleswscontrollersApiSoapControllerPortClient() {
        }
        
        public appmoduleswscontrollersApiSoapControllerPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public appmoduleswscontrollersApiSoapControllerPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public appmoduleswscontrollersApiSoapControllerPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public appmoduleswscontrollersApiSoapControllerPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string apiLogin(object username, object password) {
            return base.Channel.apiLogin(username, password);
        }
        
        public System.Threading.Tasks.Task<string> apiLoginAsync(object username, object password) {
            return base.Channel.apiLoginAsync(username, password);
        }
        
        public string apiTestWithLogin(object sessionkey, object dummytext) {
            return base.Channel.apiTestWithLogin(sessionkey, dummytext);
        }
        
        public System.Threading.Tasks.Task<string> apiTestWithLoginAsync(object sessionkey, object dummytext) {
            return base.Channel.apiTestWithLoginAsync(sessionkey, dummytext);
        }
        
        public string apiTestWithoutLogin(object dummytext) {
            return base.Channel.apiTestWithoutLogin(dummytext);
        }
        
        public System.Threading.Tasks.Task<string> apiTestWithoutLoginAsync(object dummytext) {
            return base.Channel.apiTestWithoutLoginAsync(dummytext);
        }
        
        public string apiGetTemplateForTokenId(object sessionkey, object id, string skey, string resptype) {
            return base.Channel.apiGetTemplateForTokenId(sessionkey, id, skey, resptype);
        }
        
        public System.Threading.Tasks.Task<string> apiGetTemplateForTokenIdAsync(object sessionkey, object id, string skey, string resptype) {
            return base.Channel.apiGetTemplateForTokenIdAsync(sessionkey, id, skey, resptype);
        }
        
        public string apiGetTemplateForWaveId(object sessionkey, object id, string lang_id, string resptype) {
            return base.Channel.apiGetTemplateForWaveId(sessionkey, id, lang_id, resptype);
        }
        
        public System.Threading.Tasks.Task<string> apiGetTemplateForWaveIdAsync(object sessionkey, object id, string lang_id, string resptype) {
            return base.Channel.apiGetTemplateForWaveIdAsync(sessionkey, id, lang_id, resptype);
        }
        
        public string apiLoadSurveys(object sessionkey, object items_list) {
            return base.Channel.apiLoadSurveys(sessionkey, items_list);
        }
        
        public System.Threading.Tasks.Task<string> apiLoadSurveysAsync(object sessionkey, object items_list) {
            return base.Channel.apiLoadSurveysAsync(sessionkey, items_list);
        }
        
        public string apiLoadSurveyAnswers(object sessionkey, object id, string skey, object answers_list) {
            return base.Channel.apiLoadSurveyAnswers(sessionkey, id, skey, answers_list);
        }
        
        public System.Threading.Tasks.Task<string> apiLoadSurveyAnswersAsync(object sessionkey, object id, string skey, object answers_list) {
            return base.Channel.apiLoadSurveyAnswersAsync(sessionkey, id, skey, answers_list);
        }
        
        public string apiLoadAudio(object sessionkey, object id, string skey, object answers_list) {
            return base.Channel.apiLoadAudio(sessionkey, id, skey, answers_list);
        }
        
        public System.Threading.Tasks.Task<string> apiLoadAudioAsync(object sessionkey, object id, string skey, object answers_list) {
            return base.Channel.apiLoadAudioAsync(sessionkey, id, skey, answers_list);
        }
        
        public string apiGetMonthlyNpsInfo(object sessionkey, int center, int campaign, int wave, int param_num, int param_value, int months) {
            return base.Channel.apiGetMonthlyNpsInfo(sessionkey, center, campaign, wave, param_num, param_value, months);
        }
        
        public System.Threading.Tasks.Task<string> apiGetMonthlyNpsInfoAsync(object sessionkey, int center, int campaign, int wave, int param_num, int param_value, int months) {
            return base.Channel.apiGetMonthlyNpsInfoAsync(sessionkey, center, campaign, wave, param_num, param_value, months);
        }
        
        public string apiCreateWave(object sessionkey, object wave_fields) {
            return base.Channel.apiCreateWave(sessionkey, wave_fields);
        }
        
        public System.Threading.Tasks.Task<string> apiCreateWaveAsync(object sessionkey, object wave_fields) {
            return base.Channel.apiCreateWaveAsync(sessionkey, wave_fields);
        }
    }
}
